version: "3.5"
services:
  django:
    build: ./build/django
    container_name: django.application
    restart: always
    volumes:
      - ./django:/django:rw
      - socket_app:/var/run/uwsgi
      - socket_db:/var/run/postgresql
      - static:/static
      - media:/media
    depends_on:
      - postgres
    environment:
      TZ: ${TZ}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  nginx:
    build: ./build/nginx
    container_name: django.webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./nginx/letsencrypt:/etc/letsencrypt
      - socket_app:/var/run/uwsgi
      - static:/static
      - media:/media
    depends_on:
      - django
    environment:
      TZ: ${TZ}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: django.database
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
      - socket_db:/var/run/postgresql
    environment:
      TZ: ${TZ}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  data:
    driver: local
  socket_app:
    driver: local
  socket_db:
    driver: local
  static:
    driver: local
  media:
    driver: local
