# Generated by Django 2.2.16 on 2020-11-17 11:02

import blog.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=blog.models.Base.get_str_uuid, editable=False, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='並び順')),
                ('name', models.CharField(max_length=255, verbose_name='カテゴリ名')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='スラッグ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
            ],
            options={
                'verbose_name': 'カテゴリー',
                'verbose_name_plural': 'カテゴリー',
                'db_table': 'category',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='CategoryPost',
            fields=[
                ('id', models.CharField(default=blog.models.Base.get_str_uuid, editable=False, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('category', models.CharField(max_length=255, verbose_name='カテゴリ名')),
                ('post_count', models.IntegerField(blank=True, null=True, verbose_name='記事数')),
            ],
            options={
                'verbose_name': 'カテゴリ別: 記事数',
                'verbose_name_plural': 'レポート - カテゴリ別: 記事数',
                'db_table': 'category_post',
            },
        ),
        migrations.CreateModel(
            name='CategoryTag',
            fields=[
                ('id', models.CharField(default=blog.models.Base.get_str_uuid, editable=False, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='カテゴリ名')),
                ('tag_count', models.IntegerField(blank=True, null=True, verbose_name='タグ数')),
            ],
            options={
                'verbose_name': 'カテゴリ別: タグ数',
                'verbose_name_plural': 'レポート - カテゴリ別: タグ数',
                'db_table': 'category_tag',
            },
        ),
        migrations.CreateModel(
            name='MonthPost',
            fields=[
                ('id', models.CharField(default=blog.models.Base.get_str_uuid, editable=False, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('month', models.CharField(blank=True, max_length=255, null=True, verbose_name='年月')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='タグ名')),
                ('post_count', models.IntegerField(blank=True, null=True, verbose_name='記事数')),
            ],
            options={
                'verbose_name': 'カテゴリ別: 記事数推移',
                'verbose_name_plural': 'レポート - カテゴリ別: 記事数推移',
                'db_table': 'month_post',
            },
        ),
        migrations.CreateModel(
            name='PopularPost',
            fields=[
                ('id', models.CharField(default=blog.models.Base.get_str_uuid, editable=False, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('title', models.CharField(max_length=128, verbose_name='タイトル')),
                ('link', models.CharField(max_length=255, verbose_name='リンク')),
                ('page_view', models.IntegerField(verbose_name='ページビュー')),
                ('detail_pk', models.CharField(blank=True, max_length=255, null=True, verbose_name='記事のID')),
                ('detail_is_public', models.BooleanField(default=False, verbose_name='記事の公開フラグ')),
                ('detail_published_at', models.DateTimeField(blank=True, null=True, verbose_name='記事の投稿日')),
                ('detail_category', models.CharField(blank=True, max_length=255, null=True, verbose_name='記事のカテゴリー')),
                ('detail_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='記事のタイトル')),
                ('detail_subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='記事のサブタイトル')),
                ('detail_eyecatch', models.ImageField(blank=True, null=True, upload_to='', verbose_name='記事のアイキャッチ画像')),
            ],
            options={
                'verbose_name': '人気記事',
                'verbose_name_plural': '人気記事',
                'db_table': 'popular_post',
            },
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.CharField(default=blog.models.Base.get_str_uuid, editable=False, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='並び順')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名前')),
                ('text', models.TextField(blank=True, null=True, verbose_name='内容')),
            ],
            options={
                'verbose_name': 'スニペット',
                'verbose_name_plural': 'スニペット',
                'db_table': 'snippet',
            },
        ),
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.CharField(default=blog.models.Base.get_str_uuid, editable=False, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('tag', models.CharField(blank=True, max_length=255, null=True, verbose_name='タグ名')),
                ('post_count', models.IntegerField(blank=True, null=True, verbose_name='記事数')),
            ],
            options={
                'verbose_name': 'タグ別: 記事数',
                'verbose_name_plural': 'レポート - タグ別: 記事数',
                'db_table': 'tag_post',
            },
        ),
        migrations.CreateModel(
            name='WordCloud',
            fields=[
                ('id', models.CharField(default=blog.models.Base.get_str_uuid, editable=False, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('word', models.CharField(blank=True, max_length=255, null=True, verbose_name='ワード')),
                ('word_count', models.IntegerField(blank=True, null=True, verbose_name='出現数')),
            ],
            options={
                'verbose_name': 'ワードクラウド',
                'verbose_name_plural': 'レポート - ワードクラウド',
                'db_table': 'word_cloud',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(default=blog.models.Base.get_str_uuid, editable=False, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('name', models.CharField(max_length=255, verbose_name='タグ名')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='スラッグ')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Category', verbose_name='親カテゴリー')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ',
                'db_table': 'tag',
                'ordering': ['category', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='SiteDetail',
            fields=[
                ('id', models.CharField(default=blog.models.Base.get_str_uuid, editable=False, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('keyword', models.TextField(blank=True, null=True, verbose_name='メタキーワード')),
                ('description', models.TextField(blank=True, null=True, verbose_name='メタデスクリプション')),
                ('google_analytics_html', models.TextField(blank=True, verbose_name='Google Analitics')),
                ('google_adsence_html', models.TextField(blank=True, verbose_name='Google AdSense')),
                ('github', models.CharField(blank=True, max_length=255, verbose_name='GitHub URL')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.Site', verbose_name='サイト')),
            ],
            options={
                'verbose_name': 'サイト詳細',
                'verbose_name_plural': 'サイト詳細',
                'db_table': 'sitedetail',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.CharField(default=blog.models.Base.get_str_uuid, editable=False, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('text', models.TextField(blank=True, null=True, verbose_name='本文')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.Site', verbose_name='サイト')),
            ],
            options={
                'verbose_name': 'プライバシーポリシー',
                'verbose_name_plural': 'プライバシーポリシー',
                'db_table': 'privacy_policy',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(default=blog.models.Base.get_str_uuid, editable=False, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('is_public', models.BooleanField(default=False, verbose_name='公開フラグ')),
                ('published_at', models.DateTimeField(default=datetime.datetime(1969, 12, 31, 15, 0, tzinfo=utc), help_text='Nullを回避するため、公開フラグをFalseで保存した場合はダミー日時がセットされます。その後、公開したときに日時が上書きされます。', verbose_name='投稿日')),
                ('title', models.CharField(max_length=128, verbose_name='タイトル')),
                ('subtitle', models.CharField(blank=True, max_length=128, null=True, verbose_name='サブタイトル')),
                ('eyecatch', models.ImageField(blank=True, default='image/post/eyecatch/default/default.png', null=True, upload_to='image/post/eyecatch/%Y/%m/%d/', verbose_name='アイキャッチ画像')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('text', models.TextField(blank=True, null=True, verbose_name='本文')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Category', verbose_name='カテゴリー')),
                ('related_posts', models.ManyToManyField(blank=True, related_name='_post_related_posts_+', to='blog.Post', verbose_name='関連記事')),
                ('tag', models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='タグ')),
            ],
            options={
                'verbose_name': '記事',
                'verbose_name_plural': '記事',
                'db_table': 'post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.CharField(default=blog.models.Base.get_str_uuid, editable=False, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='並び順')),
                ('link', models.URLField(blank=True, help_text='URLを指定してください', max_length=255, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Post', verbose_name='記事')),
            ],
            options={
                'verbose_name': '参考リンク',
                'verbose_name_plural': '参考リンク',
                'db_table': 'link',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.CharField(default=blog.models.Base.get_str_uuid, editable=False, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='並び順')),
                ('title', models.CharField(blank=True, help_text='画像のalt属性として利用されます', max_length=255, verbose_name='タイトル')),
                ('image', models.ImageField(blank=True, help_text='保存後、本文挿入用HTMLを生成します', null=True, upload_to='image/post/text/%Y/%m/%d/', verbose_name='画像')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Post', verbose_name='記事')),
            ],
            options={
                'verbose_name': '画像',
                'verbose_name_plural': '画像',
                'db_table': 'image',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='AboutSite',
            fields=[
                ('id', models.CharField(default=blog.models.Base.get_str_uuid, editable=False, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='image/site/author_image/', verbose_name='管理者のイメージ')),
                ('site_image', models.ImageField(blank=True, null=True, upload_to='image/site/site_image/', verbose_name='サイトのイメージ')),
                ('author_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='管理者の名前')),
                ('author_text', models.TextField(blank=True, null=True, verbose_name='管理者の説明')),
                ('site_text', models.TextField(blank=True, null=True, verbose_name='サイトの説明')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.Site', verbose_name='サイト')),
            ],
            options={
                'verbose_name': 'このサイトについて',
                'verbose_name_plural': 'このサイトについて',
                'db_table': 'about_site',
            },
        ),
    ]
