# Generated by Django 2.2.16 on 2021-02-04 13:38

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(default=blog.models.Base.get_str_uuid, editable=False, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='並び順')),
                ('title', models.CharField(blank=True, help_text='動画のalt属性として利用されます', max_length=255, verbose_name='タイトル')),
                ('video', models.FileField(blank=True, help_text='保存後、本文挿入用HTMLを生成します', null=True, upload_to='video/post/text/%Y/%m/%d/', verbose_name='動画')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Post', verbose_name='記事')),
            ],
            options={
                'verbose_name': '動画',
                'verbose_name_plural': '動画',
                'db_table': 'video',
                'ordering': ['index'],
            },
        ),
    ]
