# Generated by Django 3.1.6 on 2021-02-04 15:54

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210205_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.ImageField(blank=True, help_text='保存後、本文挿入用HTMLを生成します', null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='video/post/text/%Y/%m/%d/', validators=[cloudinary_storage.validators.validate_video], verbose_name='動画'),
        ),
    ]
