# Generated by Django 3.1.6 on 2021-02-04 15:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210205_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='保存後、本文挿入用HTMLを生成します', max_length=255, null=True, verbose_name='動画'),
        ),
    ]
