# Generated by Django 3.1.6 on 2021-02-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210205_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
    ]
