# Generated by Django 3.1.6 on 2021-02-05 03:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='eyecatch',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='アイキャッチ画像'),
        ),
    ]
