# Generated by Django 3.1.6 on 2021-02-05 04:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210205_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsite',
            name='author_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='管理者のイメージ'),
        ),
        migrations.AlterField(
            model_name='aboutsite',
            name='site_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='サイトのイメージ'),
        ),
    ]
