# Generated by Django 3.1.6 on 2021-02-05 04:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210205_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='保存後、本文挿入用HTMLを生成します', max_length=255, null=True, verbose_name='画像'),
        ),
    ]
