# Generated by Django 3.1.6 on 2021-02-05 05:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210205_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularpost',
            name='detail_eyecatch',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='記事のアイキャッチ画像'),
        ),
    ]
