# Generated by Django 2.2 on 2020-08-16 14:48

import blog.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200816_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popularpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='popularpost',
            name='id',
            field=models.CharField(default=blog.models.Base.get_str_uuid, editable=False, max_length=33, primary_key=True, serialize=False, unique=True),
        ),
    ]
