# Generated by Django 2.2 on 2020-08-17 21:55

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200816_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPost',
            fields=[
                ('id', models.CharField(default=blog.models.Base.get_str_uuid, editable=False, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('category', models.CharField(max_length=255, verbose_name='カテゴリ名')),
                ('post_count', models.IntegerField(blank=True, null=True, verbose_name='記事数')),
            ],
            options={
                'verbose_name': 'レポート - 1.カテゴリ別記事数',
                'verbose_name_plural': 'レポート - 1.カテゴリ別記事数',
                'db_table': 'category_post',
            },
        ),
        migrations.CreateModel(
            name='CategoryTag',
            fields=[
                ('id', models.CharField(default=blog.models.Base.get_str_uuid, editable=False, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='カテゴリ名')),
                ('tag_count', models.IntegerField(blank=True, null=True, verbose_name='タグ数')),
            ],
            options={
                'verbose_name': 'レポート - 2.カテゴリ別タグ数',
                'verbose_name_plural': 'レポート - 2.カテゴリ別タグ数',
                'db_table': 'category_tag',
            },
        ),
        migrations.CreateModel(
            name='MonthPost',
            fields=[
                ('id', models.CharField(default=blog.models.Base.get_str_uuid, editable=False, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('month', models.CharField(blank=True, max_length=255, null=True, verbose_name='年月')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='タグ名')),
                ('post_count', models.IntegerField(blank=True, null=True, verbose_name='記事数')),
            ],
            options={
                'verbose_name': 'レポート - 4.月別記事数',
                'verbose_name_plural': 'レポート - 4.月別記事数',
                'db_table': 'month_post',
            },
        ),
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.CharField(default=blog.models.Base.get_str_uuid, editable=False, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('tag', models.CharField(blank=True, max_length=255, null=True, verbose_name='タグ名')),
                ('post_count', models.IntegerField(blank=True, null=True, verbose_name='記事数')),
            ],
            options={
                'verbose_name': 'レポート - 3.タグ別記事数',
                'verbose_name_plural': 'レポート - 3.タグ別記事数',
                'db_table': 'tag_post',
            },
        ),
        migrations.CreateModel(
            name='WordCloud',
            fields=[
                ('id', models.CharField(default=blog.models.Base.get_str_uuid, editable=False, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('word', models.CharField(blank=True, max_length=255, null=True, verbose_name='ワード')),
                ('word_count', models.IntegerField(blank=True, null=True, verbose_name='出現数')),
            ],
            options={
                'verbose_name': 'レポート - 5.ワードクラウド',
                'verbose_name_plural': 'レポート - 5.ワードクラウド',
                'db_table': 'word_cloud',
            },
        ),
    ]
