# Generated by Django 2.2 on 2020-08-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_categorypost_categorytag_monthpost_tagpost_wordcloud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorypost',
            options={'verbose_name': 'レポート - カテゴリ別: 記事数', 'verbose_name_plural': 'レポート - カテゴリ別: 記事数'},
        ),
        migrations.AlterModelOptions(
            name='categorytag',
            options={'verbose_name': 'レポート - カテゴリ別: タグ数', 'verbose_name_plural': 'レポート - カテゴリ別: タグ数'},
        ),
        migrations.AlterModelOptions(
            name='monthpost',
            options={'verbose_name': 'レポート - カテゴリ別: 記事数推移', 'verbose_name_plural': 'レポート - カテゴリ別: 記事数推移'},
        ),
        migrations.AlterModelOptions(
            name='tagpost',
            options={'verbose_name': 'レポート - タグ別: 記事数', 'verbose_name_plural': 'レポート - タグ別: 記事数'},
        ),
        migrations.AlterModelOptions(
            name='wordcloud',
            options={'verbose_name': 'レポート - ワードクラウド', 'verbose_name_plural': 'レポート - ワードクラウド'},
        ),
        migrations.AlterField(
            model_name='sitedetail',
            name='github',
            field=models.CharField(blank=True, max_length=255, verbose_name='GitHub URL'),
        ),
    ]
