# Generated by Django 2.2 on 2020-08-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200819_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorypost',
            options={'verbose_name': 'カテゴリ別: 記事数', 'verbose_name_plural': 'レポート - カテゴリ別: 記事数'},
        ),
        migrations.AlterModelOptions(
            name='categorytag',
            options={'verbose_name': 'カテゴリ別: タグ数', 'verbose_name_plural': 'レポート - カテゴリ別: タグ数'},
        ),
        migrations.AlterModelOptions(
            name='monthpost',
            options={'verbose_name': 'カテゴリ別: 記事数推移', 'verbose_name_plural': 'レポート - カテゴリ別: 記事数推移'},
        ),
        migrations.AlterModelOptions(
            name='tagpost',
            options={'verbose_name': 'タグ別: 記事数', 'verbose_name_plural': 'レポート - タグ別: 記事数'},
        ),
        migrations.AlterModelOptions(
            name='wordcloud',
            options={'verbose_name': 'ワードクラウド', 'verbose_name_plural': 'レポート - ワードクラウド'},
        ),
    ]
