# Generated by Django 2.2.8 on 2020-08-23 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200820_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['category', 'slug'], 'verbose_name': 'タグ', 'verbose_name_plural': 'タグ'},
        ),
    ]
