# Generated by Django 2.2.8 on 2020-09-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200823_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='並び順'),
        ),
        migrations.AddField(
            model_name='link',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='並び順'),
        ),
    ]
