# Generated by Django 2.2.8 on 2020-09-06 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200906_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['index'], 'verbose_name': '画像', 'verbose_name_plural': '画像'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['index'], 'verbose_name': '参考リンク', 'verbose_name_plural': '参考リンク'},
        ),
    ]
