# Generated by Django 2.2.8 on 2020-09-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200906_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='サブタイトル'),
        ),
    ]
